[workspace]
authors = ["Ben Holme <77072232+holmeben@users.noreply.github.com>"]
channels = ["conda-forge", "https://prefix.dev/robostack-jazzy"]
name = "ros2_ws"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[target.osx-arm64.activation]
scripts = ["install/setup.zsh"]
env = { RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp" }

[feature.build.target.unix.tasks]
build = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[dependencies]
ros-jazzy-desktop-full = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
colcon-mixin = ">=0.2.3,<0.3"
cmake = ">=4.2.1,<5"
ninja = ">=1.13.2,<2"
mold = ">=2.40.4,<3"
sccache = ">=0.13.0,<0.14"
ogre-next = ">=2.3.3,<3"
ogre = ">=1.10.12.1,<2"
dartsim = ">=6.15.0,<7"
ros-jazzy-turtlebot3 = ">=2.3.3,<3"
ros-jazzy-turtlebot3-gazebo = ">=2.3.7,<3"
ros-jazzy-cartographer = ">=2.0.0,<3"
ros-jazzy-cartographer-ros = ">=2.0.9003,<3"
ros-jazzy-rviz2 = ">=14.1.12,<15"
ros-jazzy-perception = ">=0.11.0,<0.12"
ros-jazzy-perception-pcl = ">=2.6.2,<3"
ros-jazzy-pcl-ros = ">=2.6.2,<3"
ros-jazzy-pcl-conversions = ">=2.6.2,<3"
pcl = ">=1.15.0,<2"
[feature.build-tools.target.linux.dependencies]
binutils = "*"
[feature.build-tools.target.osx.dependencies]
cctools = ">=949.0.1"
ld64 = ">=530"
llvm-openmp = "*"
eigen = ">=3.4.0,<4"

[feature.lib.dependencies]
xtl = "*"
doctest = "*"

[environments.default]
features = ["lib"]

[feature.clang-base.dependencies]
clang = "*"
clangxx = "*"
[feature.clang-base.activation.env]
CC = "$CONDA_PREFIX/bin/clang"
CFLAGS = "-isystem $CONDA_PREFIX/include"
CXX = "$CONDA_PREFIX/bin/clang++"
CXXFLAGS = "-isystem $CONDA_PREFIX/include"
LDFLAGS = "-Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib"
#AMENT_PREFIX_PATH = "$AMENT_PREFIX_PATH:$CONDA_PREFIX/share"
#LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$CONDA_PREFIX/lib"

# clang-17 compiler environment
[feature.clang-17.dependencies]
clang = "17.*"
[environments.clang-17]
features = ["cmd", "build-tools", "lib", "clang-base", "clang-17"]

# clang-18 compiler environment
[feature.clang-18.dependencies]
clang = "18.*"
[environments.clang-18]
features = ["cmd", "build-tools", "lib", "clang-base", "clang-18"]

# clang-21 compiler environment
[feature.clang-21.dependencies]
clang = "21.*"
[environments.clang-21]
features = ["cmd", "build-tools", "lib", "clang-base", "clang-21"]

# clang-22
[feature.clang-22.dependencies]
clang = "22.*"
[environments.clang-22]
features = ["cmd", "build-tools", "lib", "clang-base", "clang-22"]

[feature.cmd.tasks.configure]
args = ["preset"]
cmd = """
cmake -B build/$PIXI_ENVIRONMENT_NAME/{{ preset }} -G Ninja \
  --preset {{ preset }} \
  -D CMAKE_COLOR_DIAGNOSTICS=ON \
  -D CMAKE_C_COMPILER_LAUNCHER="sccache" \
  -D CMAKE_CXX_COMPILER_LAUNCHER=sccache \
  -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
"""
inputs = ["**/CMakeLists.txt", "**/*.cmake.in", "cmake/"]
outputs = ["build/$PIXI_ENVIRONMENT_NAME/{{ preset }}/CMakeCache.txt"]
